DROP DATABASE IF EXISTS login;
CREATE DATABASE login;
USE login;

CREATE TABLE usuarios (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user VARCHAR(50) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    codigo VARCHAR(50) NOT NULL
);